package com.example.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowDownward
import androidx.compose.material.icons.filled.ArrowUpward
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.HourglassTop
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.ClipboardManager
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.domain.model.ContractDirection
import com.example.domain.model.ProductType
import com.example.domain.model.TradeOutcome
import com.example.domain.model.TradeSelection
import com.example.ui.theme.BrightGold
import com.example.ui.theme.ElectricCyan
import com.example.ui.theme.MarketGreen
import com.example.ui.theme.MarketRed
import com.example.ui.theme.TerminalBorder
import com.example.ui.theme.TerminalDarkBg
import com.example.ui.theme.TerminalSurface
import com.example.ui.theme.TerminalSurfaceHighlight
import com.example.ui.theme.TerminalSurfaceVariant
import com.example.ui.theme.TextMuted
import com.example.ui.theme.TextPrimary
import com.example.ui.theme.TextSecondary
import com.example.ui.theme.WarningOrange
import com.example.ui.theme.ZorivoPrimaryBlue

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TradeSlipSheet(
    isOpen: Boolean,
    onDismiss: () -> Unit,
    selections: List<TradeSelection>,
    userCurrencySymbol: String,
    onRemoveSelection: (String) -> Unit,
    onExecuteCashout: (selectionId: String, amount: Double) -> Unit,
    onGenerateShareCode: () -> String,
    onLoadCode: (String) -> Unit,
    onConfirmAllTrades: () -> Unit
) {
    if (!isOpen) return

    val clipboardManager: ClipboardManager = LocalClipboardManager.current
    var shareCodeGenerated by remember { mutableStateOf<String?>(null) }
    var inputCodeToLoad by remember { mutableStateOf("") }
    var codeCopiedToast by remember { mutableStateOf(false) }

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        containerColor = TerminalDarkBg,
        dragHandle = {
            Box(
                modifier = Modifier
                    .padding(vertical = 10.dp)
                    .width(44.dp)
                    .height(4.dp)
                    .background(TerminalBorder, CircleShape)
            )
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 18.dp, vertical = 6.dp)
                .testTag("trade_slip_sheet")
        ) {
            // Header Bar: Trade Slip Title, Share Code Action & Close
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        modifier = Modifier
                            .background(ElectricCyan.copy(alpha = 0.15f), RoundedCornerShape(6.dp))
                            .padding(horizontal = 8.dp, vertical = 4.dp)
                    ) {
                        Text(
                            text = "TRADE SLIP",
                            fontSize = 11.sp,
                            fontWeight = FontWeight.Black,
                            color = ElectricCyan
                        )
                    }
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "(${selections.size} Positions)",
                        fontSize = 13.sp,
                        fontWeight = FontWeight.Bold,
                        color = TextSecondary
                    )
                }

                Row(verticalAlignment = Alignment.CenterVertically) {
                    // Share Trade Slip Button
                    IconButton(
                        onClick = {
                            val code = onGenerateShareCode()
                            shareCodeGenerated = code
                            clipboardManager.setText(AnnotatedString(code))
                            codeCopiedToast = true
                        },
                        modifier = Modifier.testTag("btn_share_trade_slip")
                    ) {
                        Icon(Icons.Default.Share, contentDescription = "Share Trade Slip", tint = BrightGold, modifier = Modifier.size(20.dp))
                    }
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.Default.Close, contentDescription = "Close", tint = TextMuted)
                    }
                }
            }

            // Share / Load Code Component Banner
            Surface(
                modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp),
                shape = RoundedCornerShape(10.dp),
                color = TerminalSurfaceVariant,
                border = androidx.compose.foundation.BorderStroke(1.dp, TerminalBorder)
            ) {
                Column(modifier = Modifier.padding(10.dp)) {
                    if (shareCodeGenerated != null) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column {
                                Text("SHARE CODE GENERATED", fontSize = 10.sp, fontWeight = FontWeight.Bold, color = BrightGold)
                                Text(
                                    text = shareCodeGenerated!!,
                                    fontSize = 17.sp,
                                    fontFamily = FontFamily.Monospace,
                                    fontWeight = FontWeight.Black,
                                    color = TextPrimary
                                )
                            }
                            Text(
                                text = if (codeCopiedToast) "COPIED TO CLIPBOARD" else "Tap to copy",
                                fontSize = 10.sp,
                                fontWeight = FontWeight.Bold,
                                color = MarketGreen
                            )
                        }
                        Spacer(modifier = Modifier.height(8.dp))
                    }

                    // Load Code Input Field
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        OutlinedTextField(
                            value = inputCodeToLoad,
                            onValueChange = { inputCodeToLoad = it.uppercase() },
                            placeholder = { Text("Load Trade Slip Code (e.g. FX7K9Q2M)", fontSize = 11.sp, color = TextMuted) },
                            singleLine = true,
                            modifier = Modifier.weight(1f).height(46.dp),
                            shape = RoundedCornerShape(8.dp),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedContainerColor = TerminalSurface,
                                unfocusedContainerColor = TerminalSurface,
                                focusedBorderColor = ElectricCyan,
                                unfocusedBorderColor = TerminalBorder,
                                focusedTextColor = TextPrimary,
                                unfocusedTextColor = TextPrimary
                            )
                        )
                        Spacer(modifier = Modifier.width(6.dp))
                        Button(
                            onClick = {
                                if (inputCodeToLoad.isNotEmpty()) {
                                    onLoadCode(inputCodeToLoad)
                                    inputCodeToLoad = ""
                                }
                            },
                            modifier = Modifier.height(46.dp),
                            shape = RoundedCornerShape(8.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = BrightGold, contentColor = TerminalDarkBg)
                        ) {
                            Text("LOAD", fontSize = 11.sp, fontWeight = FontWeight.Bold)
                        }
                    }
                }
            }

            // Selections / Positions List with Real-time Early Exit / Cashout
            if (selections.isEmpty()) {
                Box(
                    modifier = Modifier.fillMaxWidth().padding(vertical = 30.dp),
                    contentAlignment = Alignment.Center
                ) {
                    Text("Your Trade Slip is currently empty.", color = TextMuted, fontSize = 13.sp)
                }
            } else {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    selections.forEach { sel ->
                        Surface(
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(10.dp),
                            color = TerminalSurface,
                            border = androidx.compose.foundation.BorderStroke(1.dp, TerminalBorder)
                        ) {
                            Column(modifier = Modifier.padding(10.dp)) {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Text(
                                            text = sel.symbol,
                                            fontWeight = FontWeight.Black,
                                            fontSize = 15.sp,
                                            color = TextPrimary
                                        )
                                        Spacer(modifier = Modifier.width(6.dp))
                                        Box(
                                            modifier = Modifier
                                                .background(
                                                    if (sel.direction == ContractDirection.HIGHER) MarketGreen.copy(alpha = 0.15f) else MarketRed.copy(alpha = 0.15f),
                                                    RoundedCornerShape(4.dp)
                                                )
                                                .padding(horizontal = 6.dp, vertical = 2.dp)
                                        ) {
                                            Text(
                                                text = sel.direction.title,
                                                fontSize = 10.sp,
                                                fontWeight = FontWeight.Bold,
                                                color = if (sel.direction == ContractDirection.HIGHER) MarketGreen else MarketRed
                                            )
                                        }
                                    }

                                    IconButton(
                                        onClick = { onRemoveSelection(sel.id) },
                                        modifier = Modifier.size(24.dp)
                                    ) {
                                        Icon(Icons.Default.Close, contentDescription = "Remove", tint = TextMuted, modifier = Modifier.size(16.dp))
                                    }
                                }

                                Spacer(modifier = Modifier.height(6.dp))

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Text(
                                        text = "Stake: $userCurrencySymbol${"%,.0f".format(sel.stake)} • Ref: $${"%,.2f".format(sel.referencePrice)}",
                                        fontSize = 11.sp,
                                        color = TextSecondary
                                    )
                                    Text(
                                        text = "Potential: $userCurrencySymbol${"%,.0f".format(sel.potentialPayout)}",
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Bold,
                                        fontFamily = FontFamily.Monospace,
                                        color = MarketGreen
                                    )
                                }

                                // Cashout / Early Exit Available Button
                                if (sel.cashoutEligible && sel.outcome == TradeOutcome.ACTIVE) {
                                    Spacer(modifier = Modifier.height(8.dp))
                                    Row(
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .background(TerminalSurfaceVariant, RoundedCornerShape(8.dp))
                                            .padding(8.dp),
                                        horizontalArrangement = Arrangement.SpaceBetween,
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Column {
                                            Text("CASHOUT AVAILABLE", fontSize = 9.sp, fontWeight = FontWeight.Black, color = BrightGold)
                                            Text(
                                                text = "Current Value: $userCurrencySymbol${"%,.0f".format(sel.currentCashoutValue)}",
                                                fontSize = 12.sp,
                                                fontFamily = FontFamily.Monospace,
                                                fontWeight = FontWeight.Bold,
                                                color = TextPrimary
                                            )
                                        }
                                        Button(
                                            onClick = { onExecuteCashout(sel.id, sel.currentCashoutValue) },
                                            colors = ButtonDefaults.buttonColors(containerColor = BrightGold, contentColor = TerminalDarkBg),
                                            shape = RoundedCornerShape(6.dp),
                                            modifier = Modifier.height(32.dp).testTag("btn_cashout_${sel.id}")
                                        ) {
                                            Text("CASHOUT NOW", fontSize = 10.sp, fontWeight = FontWeight.Black)
                                        }
                                    }
                                } else if (sel.outcome == TradeOutcome.CASHED_OUT) {
                                    Spacer(modifier = Modifier.height(4.dp))
                                    Text("✓ Early Cashout Settled into Ledger", fontSize = 11.sp, color = MarketGreen, fontWeight = FontWeight.Bold)
                                }
                            }
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(14.dp))

            // Confirm All Button
            Button(
                onClick = onConfirmAllTrades,
                enabled = selections.isNotEmpty(),
                modifier = Modifier
                    .fillMaxWidth()
                    .height(50.dp)
                    .testTag("btn_confirm_trade_slip"),
                shape = RoundedCornerShape(10.dp),
                colors = ButtonDefaults.buttonColors(containerColor = ZorivoPrimaryBlue, contentColor = Color.White)
            ) {
                Text(
                    text = if (selections.isEmpty()) "NO SELECTIONS IN SLIP" else "CONFIRM TRADE (${selections.size} SELECTIONS)",
                    fontWeight = FontWeight.Black,
                    letterSpacing = 0.5.sp,
                    fontSize = 13.sp
                )
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}
